<div class="container">
  <div class="row">
    <div class="col-md-3">
      <div class="list-group">
        <a href="/inspection" class="list-group-item">
          <h4 class="list-group-item-heading">Vistoria</h4>
            <p class="list-group-item-text">Gerencie aqui as vistorias</p>
        </a>
        <a href="/fleet/view" class="list-group-item"><i class="fa fa-search"></i> Pesquisar veículo</a>
        <a href="/inspection/view" class="list-group-item"><i class="fa fa-check-square-o"></i> Vistoriar veículo</a>
        <a href="/inspection/down" class="list-group-item active"><i class="fa fa-trash"></i> Baixa de veículo</a>
        <a href="/inspection/review-crv" class="list-group-item"><i class="fa fa-file"></i> Segunda via CRV <?if($this->vehiclesAskedCrv){?><span class="badge"><?=$this->vehiclesAskedCrv?></span><?}?></a>
      </div>
    </div>
    <div class="col-md-9">
    	<ol class="breadcrumb">
        <li><a href="/dashboard">Página inicial</a></li>
        <li class="active">Baixa de veículo</li>
      </ol>
      <div class="page-header">
        <h1>Baixa <small>defina aqui as baixas de veículo</small></h1>
        <hr>
        <table class="table table-hover table-bordered">
          <thead>
            <th>Placa</th>
            <th>Renavam</th>
            <th>Ações</th>
          </thead>
          <tbody>
            <?if(count($this->list)){
              foreach($this->list as $body){?>
                <tr>
                  <td><a href="/fleet/edit/id/<?=$body->id?>"><?=$body->plate?></a></td>
                  <td><?=$body->renavam?></td>
                  <td>
                  	<a href="#accept_<?=$body->id?>" class="btn btn-success btn-sm help" data-toggle="modal" title="" data-original-title="Aceitar baixa"><span class="glyphicon glyphicon-thumbs-up"></span></a>
                  	<a href="#deny_<?=$body->id?>" class="btn btn-danger btn-sm help" data-toggle="modal" title="" data-original-title="Rejeitar baixa"><span class="glyphicon glyphicon-thumbs-down"></span></a>
                  	</td>
                </tr>
            <?} } else{?>
              <tr>
                <td colspan="7"><h4>Não há veículos esperando para baixa.</h4></td>
              </tr>
            <?}?>
          </tbody>
        </table>
        <?if(is_object($this->list) && !isset($this->list->name)){ echo $this->paginationControl($this->list,'Sliding','pagination.phtml'); }?>
      </div>
    </div>
  </div>
</div>



<?if(count($this->list)){
  foreach($this->list as $body){?>
  <form action="/inspection/accept-down" method="post">
    <div class="modal fade" id="accept_<?=$body->id?>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h4 class="modal-title">Finalizar Processo</h4>
          </div>
          <div class="modal-body">
            <p>Tem certeza que deseja aceitar o pedido de baixa do veículo <strong><?=$body->plate?></strong>?</p>
          </div>
          <div class="modal-footer">
            <input type="hidden" name="vehicle_id" value="<?=$body->id?>">
            <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
            <button type="submit" class="btn btn-success">Aceitar baixa</button>
          </div>
        </div><!-- /.modal-content -->
      </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->
  </form>

  <form action="/inspection/deny-down" method="post">
    <div class="modal fade" id="deny_<?=$body->id?>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h4 class="modal-title">Finalizar Processo</h4>
          </div>
          <div class="modal-body">
            <p>Tem certeza que deseja rejeitar o pedido de baixa do veículo <strong><?=$body->plate?></strong>?</p>
          </div>
          <div class="modal-footer">
            <input type="hidden" name="vehicle_id" value="<?=$body->id?>">
            <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
            <button type="submit" class="btn btn-danger">Rejeitar baixa</button>
          </div>
        </div><!-- /.modal-content -->
      </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->
  </form>
<?} }?>
