<div class="container">
  <div class="row">
    <div class="col-md-3">
      <div class="list-group">
        <a href="/fleet" class="list-group-item">
          <h4 class="list-group-item-heading">Vistoria</h4>
            <p class="list-group-item-text">Gerencie as vistorias</p>
        </a>
      </div>
    </div>
    <div class="col-md-9">
    	<ol class="breadcrumb">
        <li><a href="/dashboard">Página inicial</a></li>
        <li><a href="/fleet">Vistoria</a></li>
        <li class="active">Conclusão</li>
      </ol>
      <div class="page-header">
        <div class="jumbotron">
          <h1>Veículo salvo!</h1>
          <p class="lead">O processo de vistoria do veículo foi concluído com sucesso. A SETOP analisará toda a documentação e encaminhará a certidão do veículo ao consórcio proprietário do ônibus.</p>
          <p><a class="btn btn-lg btn-success" href="/inspection/view">Ok!</a></p>
        </div>
      </div>
    </div>
  </div>
</div>