
<!DOCTYPE html>
<html lang="pt_BR">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Um sistema de gestão do transporte municipal de ônibus">
    <meta name="author" content="IMTT">

    <title>IMTT | Ônibus Municipal</title>

    <!-- Bootstrap core CSS -->
    <link href="/css/bootstrap.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="/css/justified-nav.css" rel="stylesheet">

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="/js/html5shiv.js"></script>
      <script src="/js/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <div class="container">

      <div class="masthead">
        <h3 class="text-muted">IMTT</h3>
      </div>

      <!-- Jumbotron -->
      <div class="jumbotron">
        <h1>SGTM</h1>
        <p class="lead">Um sistema de gestão do transporte municipal de ônibus.</p>
        <p><a class="btn btn-lg btn-success" href="auth/login">Entrar</a></p>
      </div>

    </div> <!-- /container -->

  </body>
</html>
