<div class="container">
  <div class="row">
    <div class="col-md-3">
      <div class="list-group">
        <a href="/rate-calculation/cost" class="list-group-item">
          <h4 class="list-group-item-heading">Custos</h4>
            <p class="list-group-item-text">Gerencie aqui os dados dos custos</p>
        </a>
        <a href="/rate-calculation/fix-cost" class="list-group-item"><i class="fa fa-lock"></i> Custos fixos</a>
        <a href="/rate-calculation/variable-cost" class="list-group-item"><i class="fa fa-unlock"></i> Custos variáveis </a>
      </div>
    </div>
    <div class="col-md-9">
      <ol class="breadcrumb">
        <li><a href="/dashboard">Dashboard</a></li>
        <li><a href="/rate-calculation">Cálculo de tarifa</a></li>
        <li class="active">Custos</li>
      </ol> 
      <div class="jumbotron">
        <h1>Custos</h1>
        <p class="lead">O módulo <b>Custos</b> dá suporte ao cálculo de tarifas, contendo aqui os custos fixos e variáveis considerados no cálculo.</p>
      </div>
      <div class="text-center">
        <img class="img-responsive img-thumbnail" src="/img/cost.jpg" width="900px"><br><br>
      </div>
     </div>
    </div>
  </div>