<div class="container">
  <div class="row">
    <div class="col-md-3">
      <div class="list-group">
        <a href="/rate-calculation/fix-cost" class="list-group-item">
          <h4 class="list-group-item-heading">Custos fixos</h4>
            <p class="list-group-item-text">Gerencie aqui os dados dos custos fixos</p>
        </a>
        <a href="/rate-calculation/vehicle-depreciation" class="list-group-item"><i class="fa fa-line-chart"></i> Depreciação do veículo</a>
        <a href="/rate-calculation/vehicle-remuneration" class="list-group-item"><i class="fa fa-money"></i> Remuneração do veículo </a>
        <a href="/rate-calculation/lift-remuneration" class="list-group-item"><i class="fa fa-sort"></i> Remuneração do elevador </a>
        <a href="/rate-calculation/equipment-remuneration" class="list-group-item"><i class="fa fa-lightbulb-o"></i> Remuneração de instalações e equipamentos </a>
        <a href="/rate-calculation/warehouse-remuneration" class="list-group-item"><i class="fa fa-scissors"></i> Remuneração de almoxarifado </a>
        <a href="/rate-calculation/eletronic-ticketing" class="list-group-item"><i class="fa fa-credit-card"></i> Sistema de bilhetagem eletrônica</a>
        <a href="/rate-calculation/operation-crew" class="list-group-item"><i class="fa fa-group"></i> Pessoal de operação </a>
        <a href="/rate-calculation/fixed-expenses" class="list-group-item"><i class="fa fa-dollar"></i> Despesas fixas </a>
        <a href="/rate-calculation/social-charges" class="list-group-item"><i class="fa fa-paste"></i> Encargos sociais </a>
      </div>
    </div>
    <div class="col-md-9">
      <ol class="breadcrumb">
        <li><a href="/dashboard">Dashboard</a></li>
        <li><a href="/rate-calculation">Cálculo de tarifa</a></li>
        <li><a href="/rate-calculation/cost">Custos</a></li>
        <li class="active">Custos fixos</li>
      </ol> 
      <div class="jumbotron">
        <h1>Custos fixos</h1>
        <p class="lead">O módulo <b>Custos fixos</b> dá suporte ao cálculo de tarifas, contendo os dados dos custos variáveis.</p>
      </div>
      <div class="text-center">
        <img class="img-responsive img-thumbnail" src="/img/fix-costs.jpg" width="900px"><br><br>
      </div>
     </div>
    </div>
  </div>