<div class="container">
  <div class="row">
    <div class="col-md-3">
      <div class="list-group">
        <a href="/rate-calculation" class="list-group-item">
          <h4 class="list-group-item-heading">Cálculo de tarifa</h4>
            <p class="list-group-item-text">Gerencie aqui os dados do cálculo de tarifa</p>
        </a>
        <a href="/rate-calculation/new" class="list-group-item"><i class="fa fa-pencil"></i> Novo</a>
        <a href="/rate-calculation/view" class="list-group-item"><i class="fa fa-search"></i> Pesquisar</a>
        <a href="/rate-calculation/cost" class="list-group-item"><i class="fa fa-calculator"></i> Custos </a>
      </div>
    </div>
    <div class="col-md-9">
      <ol class="breadcrumb">
        <li><a href="/dashboard">Página inicial</a></li>
        <li class="active">Cálculo de Tarifa</li>
      </ol> 
      <div class="jumbotron">
        <h1>Cálculo de Tarifa</h1>
        <p class="lead">O módulo <b>Cálculo de Tarifa</b> dá suporte ao cálculo de tarifas.</p>
      </div>
      <div class="text-center">
        <img class="img-responsive img-thumbnail" src="/img/tarifa.jpg"><br><br>
      </div>
     </div>
    </div>
  </div>