<div class="container">
  <div class="row">
    <div class="col-md-3">
      <div class="list-group">
        <a href="/rate-calculation/variable-cost" class="list-group-item">
          <h4 class="list-group-item-heading">Custos variáveis</h4>
            <p class="list-group-item-text">Gerencie aqui os dados dos custos variáveis</p>
        </a>
        <a href="/rate-calculation/fuel" class="list-group-item"><i class="fa fa-tint"></i> Combustível</a>
        <a href="/rate-calculation/lubricant" class="list-group-item"><i class="fa fa-life-ring"></i> Lubrificantes </a>
        <a href="/rate-calculation/tread" class="list-group-item"><i class="fa fa-dashboard"></i> Rodagem </a>
        <a href="/rate-calculation/accessories" class="list-group-item"><i class="fa fa-gears"></i> Peças e acessórios </a>
        <a href="/rate-calculation/km-production" class="list-group-item"><i class="fa fa-road"></i> Produção quilométrica </a>
      </div>
    </div>
    <div class="col-md-9">
      <ol class="breadcrumb">
        <li><a href="/dashboard">Dashboard</a></li>
        <li><a href="/rate-calculation">Cálculo de tarifa</a></li>
        <li><a href="/rate-calculation/cost">Custos</a></li>
        <li class="active">Custos variáveis</li>
      </ol> 
      <div class="jumbotron">
        <h1>Custos variáveis</h1>
        <p class="lead">O módulo <b>Custos variáveis</b> dá suporte ao cálculo de tarifas, contendo os dados dos custos variáveis.</p>
      </div>
      <div class="text-center">
        <img class="img-responsive img-thumbnail" src="/img/variable_cost.jpg"><br><br>
      </div>
    </div>
    </div>
  </div>