<div class="container">
  <div class="row">
    <div class="col-md-3">
      <div class="list-group">
        <a href="/rate-calculation" class="list-group-item">
          <h4 class="list-group-item-heading">Cálculo de tarifa</h4>
            <p class="list-group-item-text">Gerencie aqui os dados do cálculo de tarifa</p>
        </a>
        <a href="/rate-calculation/new" class="list-group-item"><i class="fa fa-pencil"></i> Novo</a>
        <a href="#" class="list-group-item active"> Pesquisar</a>
        <a href="/rate-calculation/coefficient" class="list-group-item"><i class="fa fa-calculator"></i> Coeficientes </a>
      </div>
    </div>
    <div class="col-md-9">
      <ol class="breadcrumb">
        <li><a href="/dashboard">Dashboard</a></li>
        <li><a href="/rate-calculation">Cálculo de tarifa</a></li>
        <li class="active">Pesquisa</li>
      </ol> 
     </div>
    </div>
  </div>