<div class="container">
  <div class="row">
    <div class="col-md-3">
	  	<div class="list-group">
	  		<a href="/mco" class="list-group-item">
	  			<h4 class="list-group-item-heading">MCO</h4>
    				<p class="list-group-item-text">Gerencie aqui os dados dos MCO's</p>
	  		</a>
			   <a href="/mco/analytics-result/id/<?=$this->mcoId?>" class="list-group-item"><span class="glyphicon glyphicon-inbox"></span> Dados Operacionais</a>
			  <a href="/mco/analytics-adjustments/id/<?=$this->mcoId?>" class="list-group-item"><span class="glyphicon glyphicon-transfer"></span> Ajustes de Catraca</a>
			  <a href="/mco/analytics-diff/id/<?=$this->mcoId?>" class="list-group-item active"><span class="glyphicon glyphicon-minus-sign"></span> Diferenças de Catraca</a>
			  <a href="/mco/analytics-finance/id/<?=$this->mcoId?>" class="list-group-item"><span class="glyphicon glyphicon-log-in"></span> Receita</a>
			  <?$mcoData = new Application_Model_DbTable_Mco();
          $lockDay = $mcoData->fetchRow($mcoData->select()->where('id = ?',$this->mcoId));
          if($lockDay->lock_day ==1){?>
           <a href="/mco/main-new-lost-log/id/<?=$this->mcoId?>" class="list-group-item"><span class="fa fa-bookmark"></span> Perda de Log</a>
        <?}?>
			</div>
		</div>
    <div class="col-md-9">
      <ol class="breadcrumb">
        <li><a href="/dashboard">Página inicial</a></li>
        <li><a href="/mco/">MCO</a></li>
        <li><a href="/mco/view">Pesquisa</a></li>
        <li><a href="/mco/analytics-by-day/id/<?=$this->mcoId?>">Análise</a></li>
        <li class="active">Diferenças</li>
      </ol> 
      <div class="page-header">
        <h1>MCO<small> dados da bilhetagem eletrônica</small></h1>
        <hr>
          <form class="form-inline" action="/mco/analytics-diff/id/<?=$this->mcoId?>" method="get" role="form">
            <div class="form-group col-md-5">
            <input type="text" class="form-control" placeholder="pesquisa" name="field" value="<?=$this->field?>" id="textSearch">
            </div>
            <div class="form-group col-md-3">
              <select name="option" class="form-control" id="search">
                <option value="0">Pesquisar por:</option>
                <option value="1" <?if($this->option == 1) echo 'selected="selected"';?>>Linha</option>
                <option value="2" <?if($this->option == 2) echo 'selected="selected"';?>>Veículo</option>
              </select>
            </div> 
            <button type="submit" class="btn btn-primary">Pesquisar</button>
          </form>
          <hr>
        <table class="table table-hover table-bordered">
          <thead>
            <th>Linha</th>
            <th>Veículo</th>
            <th>Roleta anterior</th>
            <th>Roleta posterior</th>
            <th>Data anterior</th>
            <th>Data posterior</th>
            <th>Diferença de passageiros</th>
            <?if($lockDay->lock_day ==1){?>     
                <th>Abonar passageiros</th>
            <?}?>
          </thead>
          <tbody>
            <?if(is_object($this->list) && !isset($this->list->name)){
              foreach($this->list as $body){?>
                <tr>
                  <td><?=$body->line?></td>
                  <td><?=$body->vehicle?></td>
                  <td><?=$body->roulette_before?></td>
                  <td><?=$body->roulette_after?></td>
                  <td><?=Application_Model_General::dateToBr($body->date_before)?></td>
                  <td><?=Application_Model_General::dateToBr($body->date_after)?></td>
                  <td><?=$body->roulette_after - $body->roulette_before?></td>
                  <?if($lockDay->lock_day ==1){?>
                      <td><a href="/mco/accredit-passenger/id/<?=$body->id?>/mco_id/<?=$body->mco_id?>" class="btn btn-success help" data-toggle="modal" title="Abonar passageiros"><span class="glyphicon glyphicon-thumbs-up"></span></a></td>
                  <?}?>
                </tr>
            <?} } else{?>
              <tr>
                <td colspan="7">Não foi encontrado nenhum veículo na pesquisa.</td>
              </tr>
            <?}?>
          </tbody>
        </table>
        <?if(is_object($this->list) && !isset($this->list->name)){ echo $this->paginationControl($this->list,'Sliding','pagination.phtml', array('field' => $this->field,'option' => $this->option)); }?>
      </div>
    </div>
  </div>
</div>