<div class="container">
  <div class="row">
    <div class="col-md-3">
      <div class="list-group">
        <a href="/mco" class="list-group-item">
          <h4 class="list-group-item-heading">MCO</h4>
            <p class="list-group-item-text">Gerencie aqui os dados dos MCO's</p>
        </a>
        <a href="/mco/new" class="list-group-item"><i class="fa fa-pencil"></i> Novo</a>
        <a href="/mco/view" class="list-group-item"><i class="fa fa-search"></i> Pesquisar</a>
        <a href="/mco/report" class="list-group-item"><span class="glyphicon glyphicon-list-alt"></span> Relatórios</a>
      </div>
    </div>
    <div class="col-md-9">
      <ol class="breadcrumb">
        <li><a href="/dashboard">Página inicial</a></li>
        <li class="active">MCO</li>
      </ol> 
      <div class="jumbotron">
        <h1>MCO</h1>
        <p class="lead">O Mapa de Controle Operacional é todo o dado resultante da bilhetagem eletrônica do sistema municipal de transporte.</p>
      </div>
      <div class="text-center">
        <img class="img-responsive img-thumbnail" src="/img/mco.jpg"><br><br>
      </div>
     </div>
    </div>
  </div>
