<div class="container"><br>
	<table style="text-align: center; height: 60%;width: 80%; margin: 0 auto" class="table table-bordered" border='2'>
      <tr>
        <th style="border: 2px solid white; border-color: #000; height: 185px ;width: 200px"><img alt="" src="/img/brasao2.jpg" height="100%" width="100%" align="center"></th>
        <th style="border: 2px solid white; border-color: #000; text-align: center; line-height: 55px"><font size="3" face="verdana">Superintendência de Transporte Municipal</font><br>
        <img width="100%" src="/img/barra.jpg"><br><font face="verdana" size="3">Relatório de Composição da Receita</font></th>
      </tr>
    </table>
    <br>
    <h3 align="center"><?=$this->startDate?> até <?=$this->endDate?></h3>
	<br>
	<div class="row">
		<div class="col-sm-12"><br><br>
			<table class="table table-bordered table-hover" border="1">
				<thead>
					<tr>
						<th>Tarifa</th>
						<th>Passageiros</th>
						<th>Porcentagem</th>
						<th>Receita Bruta</th>
						<th>Porcentagem</th>
					</tr>
				</thead>
				<tbody>
				<?if (count($this->listFares)) {
						foreach ($this->listFares as $fares){?>
							<tr>
								<td>R$ <?=number_format($fares->value, 2, ",", ".")?></td>
								<td><?=number_format($fares->amount, 0, ",", ".")?></td>
								<td><?=number_format(($fares->amount/$this->fareRevenue['totalPassengers'])*100, 2, ",", ".")?>%</td>
								<td>R$ <?=number_format($fares->revenue, 2, ",", ".")?></td>
								<td><?=number_format(($fares->revenue/$this->fareRevenue['totalRevenue'])*100, 2, ",", ".")?> %</td>
							</tr>
						<?
						}?>
							<tr>
								<td><strong>Total</strong></td>
								<td><strong><?=number_format($this->fareRevenue['totalPassengers'], 0, ",", ".")?></strong></td>
								<td><strong>100%</strong></td>
								<td><strong>R$ <?=number_format($this->fareRevenue['totalRevenue'], 2, ",", ".")?></strong></td>
								<td><strong>100%</strong></td>
							</tr>
				<?}?>
				</tbody>
			</table>
		</div>
	</div>
	<div class="row">
		<div class="col-sm-12">
			<table class="table table-bordered table-hover" border="1">
				<thead>
					<tr>
						<th>Pagamento</th>
						<th>Passageiros</th>
						<th>Porcentagem</th>
						<th>Receita Bruta</th>
						<th>Porcentagem</th>
						<th>Repasse CBTU</th>
						<th>Porcentagem</th>
						<th>Receita líquida</th>
						<th>CGO</th>
					</tr>
				</thead>
				<tbody>
					<?foreach($this->groupFares as $fares){
						if(isset($fares['type'])){?>
					<tr>
						<td><?=$fares['type']?></td>
						<td><?=number_format($fares['amount'],0,"",".")?></td>
						<td><?=number_format($fares['amount']/$this->groupFares['totalPassengers']*100, 2, ",", ".")?>%</td>
						<td>R$ <?=number_format($fares['revenue'], 2, ",", ".")?></td>
						<td><?=number_format($fares['revenue']/$this->groupFares['totalRevenue']*100, 2, ",", ".")?>%</td>
						<td>R$ <?=number_format($fares['amount']*$fares['diff'], 2, ",", ".")?></td>
						<td><?=number_format(($fares['amount']*$fares['diff'])/$this->groupFares['totalCbtu']*100, 2, ",", ".")?>%</td>
						<td>R$ <?=number_format($fares['revenue']-($fares['amount']*$fares['diff']), 2, ",", ".")?></td>
						<td>R$ <?=number_format(($fares['revenue']-($fares['amount']*$fares['diff']))*0.04, 2, ",", ".")?></td>
					</tr>
					<?}}?>
					<tr>
						<td><strong>Total</strong></td>
						<td><strong><?=number_format($this->groupFares['totalPassengers'],0,"",".")?></strong></td>
						<td><strong>100%</strong></td>
						<td><strong>R$ <?=number_format($this->groupFares['totalRevenue'],2,",",".")?></strong></td>
						<td><strong>100%</strong></td>
						<td><strong>R$ <?=number_format($this->groupFares['totalCbtu'], 2, ",", ".")?></strong></td>
						<td><strong>100%</strong></td>
						<td><strong>R$ <?=number_format($this->groupFares['totalRevenue']-$this->groupFares['totalCbtu'], 2, ",", ".")?></strong></td>
						<td><strong>R$ <?=number_format(($this->groupFares['totalRevenue']-$this->groupFares['totalCbtu'])*0.04, 2, ",", ".")?></strong></td>
					</tr>
				</tbody>
			</table>
		</div>
	</div>
</div>