<div class="container">
  <div class="row">
    <div class="col-md-3">
      <div class="list-group">
        <a href="/dashboard" class="list-group-item">
          <h4 class="list-group-item-heading">Página inicial</h4>
            <p class="list-group-item-text">SGTM</p>
        </a>
        <?php $authNamespace = new Zend_Session_Namespace('userInformation');
        if($authNamespace->institution == 1 || $authNamespace->institution == 3 || $authNamespace->institution == 4){?>
        <a href="/fleet" class="list-group-item"><i class="fa fa-truck"></i> Frota</a>
        <?php }
        if($authNamespace->institution == 1){?>
        <a href="/inspection" class="list-group-item"><i class="fa fa-fire-extinguisher"></i> Vistoria</a>
        <a href="/scheduling" class="list-group-item"><i class="fa fa-calendar"></i> Agendamento online</a>
        <?php }
        if($authNamespace->institution == 3){?>
        <a href="/validator" class="list-group-item"><i class="glyphicon glyphicon-barcod"></i> Validador</a>
        <?php }?>
      </div>
    </div>
    <div class="col-md-9">
    	<ol class="breadcrumb">
        <li class="active">Página inicial</li>
      </ol>
      <div class="text-center">
		    <img src='/img/onibus.jpg' class="img-responsive img-thumbnail"><br><br>
		  </div>
		 </div>
		</div>
	</div>
