<div class="container">
  <div class="row">
    <div class="col-md-3">
      <div class="list-group">
        <a href="/fleet" class="list-group-item">
          <h4 class="list-group-item-heading">Frota</h4>
            <p class="list-group-item-text">Gerencie aqui os dados da frota</p>
        </a>
        <?if($this->institution == 3){?>
        <a href="/fleet/new" class="list-group-item"><span class="glyphicon glyphicon-pencil"></span> Novo</a>
        <?}?>
        <a href="/fleet/view" class="list-group-item"><span class="glyphicon glyphicon-search"></span> Pesquisar</a>
        <a href="/fleet/review" class="list-group-item"><span class="glyphicon glyphicon-check"></span> Cadastros realizados <?if($this->vehiclesReviewed){?><span class="badge"><?=$this->vehiclesReviewed?></span><?}?></a>
        <a href="/fleet/review-transfer" class="list-group-item active"><i class="fa fa-exchange"></i> Transferências <?if($this->vehiclesTransfered){?><span class="badge"><?=$this->vehiclesTransfered?></span><?}?></a>
        <a href="/fleet/review-crv" class="list-group-item"><i class="fa fa-file"></i> Segunda via CRV <?if($this->vehiclesAskedCrv){?><span class="badge"><?=$this->vehiclesAskedCrv?></span><?}?></a>
        <a href="/inspection/down" class="list-group-item"><i class="fa fa-trash"></i> Baixa de veículo</a>
      </div>
    </div>
    <div class="col-md-9">
      <ol class="breadcrumb">
        <li><a href="/dashboard">Página inicial</a></li>
        <li><a href="/fleet">Frota</a></li>
        <li class="active">Transferências</li>
      </ol>
      <div class="page-header">
        <h1>Transferências <small> transferências realizadas pelos consórcios</small></h1>
        <hr>
        <table class="table table-hover table-bordered">
          <thead>
            <th>Placa</th>
            <th>Consórcio anterior</th>
            <th>Consórcio transferido</th>
            <th>Ação</th>
          </thead>
          <tbody>
            <?if(is_object($this->list) && !isset($this->list->name)){
              foreach($this->list as $body){?>
                <tr>
                  <td><?=$body->plate?></td>
                  <td><?=$body->pre_consortium?></td>
                  <td><?=$body->pos_consortium?></td>
                  <td>
                    <a href="/fleet/vis/id/<?=$body->historic_id?>" class="btn btn-default btn-sm help" title="Visualizar dados do veículo"><i class="fa fa-eye"></i></a>
                  	<a href="#accept_<?=$body->id?>" class="btn btn-success btn-sm help" data-toggle="modal" title="Aceitar transferência"><span class="glyphicon glyphicon-thumbs-up"></span></a>
                  	<a href="#deny_<?=$body->id?>" class="btn btn-danger btn-sm help" data-toggle="modal" title="Rejeitar transferência"><span class="glyphicon glyphicon-thumbs-down"></span></a>
                  </td>
                </tr>
            <?} } else{?>
              <tr>
                <td colspan="7">Não foi encontrado nenhum veículo para revisão.</td>
              </tr>
            <?}?>
          </tbody>
        </table>
        <?if(is_object($this->list) && !isset($this->list->name)){ echo $this->paginationControl($this->list,'Sliding','pagination.phtml'); }?>
      </div>
    </div>
  </div>
</div>

<?foreach($this->list as $body){?>
<form method="post" action="/fleet/accept-transfer">
  <div class="modal fade" id="accept_<?=$body->id?>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title" id="myModalLabel">Aceitar Transferência</h4>
        </div>
        <div class="modal-body">
          Tem certeza que deseja aceitar a transferência deste veículo?
        </div>
        <div class="modal-footer">
          <input type="hidden" value="<?=$body->id?>" name="id">
          <input type="hidden" value="<?=$body->vehicle_id?>" name="vehicle_id">
          <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
          <input type="submit" class="btn btn-success" value="Aceitar">
        </div>
      </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
  </div><!-- /.modal -->
</form>

<form method="post" action="/fleet/deny-transfer">
  <div class="modal fade" id="deny_<?=$body->id?>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title" id="myModalLabel">Rejeitar Transferência</h4>
        </div>
        <div class="modal-body">
          Tem certeza que deseja rejeitar a transferência deste veículo?
        </div>
        <div class="modal-footer">
          <input type="hidden" value="<?=$body->id?>" name="id">
          <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
          <input type="submit" class="btn btn-danger" value="Não aceitar">
        </div>
      </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
  </div><!-- /.modal -->
</form>
<?}?>