<div class="container">
  <div class="row">
    <div class="col-md-3">
      <div class="list-group">
        <a href="/fleet" class="list-group-item">
          <h4 class="list-group-item-heading">Frota</h4>
            <p class="list-group-item-text">Gerencie aqui os dados da frota</p>
        </a>
        <?if($this->institution == 3){?>
        <a href="/fleet/new" class="list-group-item"><span class="glyphicon glyphicon-pencil"></span> Novo</a>
        <?}?>
        <a href="/fleet/view" class="list-group-item"><span class="glyphicon glyphicon-search"></span> Pesquisar</a>
        <a href="/fleet/review" class="list-group-item"><span class="glyphicon glyphicon-check"></span> Cadastros realizados <?if($this->vehiclesReviewed){?><span class="badge"><?=$this->vehiclesReviewed?></span><?}?></a>
        <a href="/fleet/review-transfer" class="list-group-item"><i class="fa fa-exchange"></i> Transferências <?if($this->vehiclesTransfered){?><span class="badge"><?=$this->vehiclesTransfered?></span><?}?></a>
        <a href="/fleet/review-crv" class="list-group-item active"><i class="fa fa-file"></i> Segunda via CRV <?if($this->vehiclesAskedCrv){?><span class="badge"><?=$this->vehiclesAskedCrv?></span><?}?></a>
        <a href="/inspection/down" class="list-group-item"><i class="fa fa-trash"></i> Baixa de veículo</a>
      </div>
    </div>
    <div class="col-md-9">
      <ol class="breadcrumb">
        <li><a href="/dashboard">Página inicial</a></li>
        <li><a href="/fleet">Frota</a></li>
        <li class="active">Segunda via CRV</li>
      </ol>
      <div class="page-header">
        <h1>Segunda via CRV <small> pedidos de segunda via de CRV</small></h1>
        <hr>
        <table class="table table-hover table-bordered">
          <thead>
            <th>Placa</th>
            <th>Justificativa</th>
            <th>Ação</th>
          </thead>
          <tbody>
            <?if(is_object($this->list) && !isset($this->list->name)){
              foreach($this->list as $body){?>
                <tr>
                  <td><?=$body->plate?></td>
                  <td><?=$body->justify?></td>
                  <td>
                  	<a href="#accept_<?=$body->id?>" class="btn btn-success btn-sm help" data-toggle="modal" title="Emitir segunda via"><span class="glyphicon glyphicon-thumbs-up"></span></a>
                  </td>
                </tr>
            <?} } else{?>
              <tr>
                <td colspan="7">Não foi encontrado nenhum veículo para revisão.</td>
              </tr>
            <?}?>
          </tbody>
        </table>
        <?if(is_object($this->list) && !isset($this->list->name)){ echo $this->paginationControl($this->list,'Sliding','pagination.phtml'); }?>
      </div>
    </div>
  </div>
</div>

<?foreach($this->list as $body){?>
<form method="post" action="/fleet/accept-crv">
  <div class="modal fade" id="accept_<?=$body->id?>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title" id="myModalLabel">Aceitar Alteração</h4>
        </div>
        <div class="modal-body">
          Tem certeza que deseja emitir a segunda via de CRV deste veículo?
          <br>
          <br>
          <div class="form-group">
              <label class="col-sm-2">Período</label>
                <div class="col-sm-2">
                  <textarea class="form-control" name="period" rows="1"></textarea>
                </div>
            </div>
            <br>
            <br>
            <div class="form-group">
              <label class="col-sm-2">Validade</label>
                <div class="col-sm-6">
                  <select name="validity" class="form-control">
                    <option>-- Selecione Anos/Meses --</option>
                    <option>MÊS</option>
                    <option>ANO</option>
                    <option>MESES</option>
                    <option>ANOS</option></select>
                </div>
            </div>
        </div>
        <br>
        <br>  
        <div class="modal-footer">
            <input type="hidden" value="<?=$body->vehicle_id?>" name="id">
            <input type="hidden" value="1" name="crv">
            <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
            <button type="submit" class="btn btn-success">Confirmar</button>
        </div>
      </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
  </div><!-- /.modal -->
</form>

<?}?>