<div class="container">
  <div class="row">
    <div class="col-md-3">
      <div class="list-group">
        <a href="/fleet" class="list-group-item">
          <h4 class="list-group-item-heading">Frota</h4>
            <p class="list-group-item-text">Gerencie aqui os dados da frota</p>
        </a>
        <a href="/fleet/new" class="list-group-item"><span class="glyphicon glyphicon-pencil"></span> Novo</a>
        <a href="/fleet/view" class="list-group-item"><span class="glyphicon glyphicon-search"></span> Pesquisar</a>
        <a href="/fleet/report" class="list-group-item"><span class="glyphicon glyphicon-list-alt"></span> Relatórios</a>
        <a href="/fleet/review" class="list-group-item"><span class="glyphicon glyphicon-check"></span> Cadastros realizados <?if($this->vehiclesReviewed){?><span class="badge"><?=$this->vehiclesReviewed?></span><?}?></a>
        <a href="/fleet/review-transfer" class="list-group-item"><i class="fa fa-exchange"></i> Transferências <?if($this->vehiclesTransfered){?><span class="badge"><?=$this->vehiclesTransfered?></span><?}?></a>
        <a href="/fleet/review-crv" class="list-group-item"><i class="fa fa-file"></i> Segunda via CRV <?if($this->vehiclesAskedCrv){?><span class="badge"><?=$this->vehiclesAskedCrv?></span><?}?></a>
      </div>
    </div>
    <div class="col-md-9">
      <ol class="breadcrumb">
        <li><a href="/dashboard">Página inicial</a></li>
        <li><a href="/fleet">Frota</a></li>
        <li class="active">Revisão</li>
      </ol>
      <div class="page-header">
        <h1>Revisão de edição <small>gerencie aqui os dados alterados pelo DER-MG</small></h1>
        <hr>
        <table class="table table-hover table-bordered">
          <thead>
            <th>Placa</th>
            <th>Número de Ordem</th>
            <th>Consórcio</th>
            <th>Ação</th>
          </thead>
          <tbody>
            <?if(is_object($this->list) && !isset($this->list->name)){
              foreach($this->list as $body){?>
                <tr>
                  <td><?=$body->plate?></td>
                  <td><?=$body->external_number?></td>
                  <td><?=$body->consortium_name?></td>
                  <td>
                    <a href="/fleet/vis/id/<?=$body->historic_id?>" class="btn btn-default btn-sm help" title="Visualizar dados do veículo"><i class="fa fa-eye"></i></a>
                    <a href="/fleet/edit/id/<?=$body->vehicle_id?>" class="btn btn-default btn-sm help" title="Editar veículo"><i class="fa fa-pencil"></i></a>
                  	<a class="btn btn-success btn-sm help" data-toggle="modal" title="Aceitar cadastro" data-target="#accept_<?=$body->vehicle_id?>"><span class="glyphicon glyphicon-thumbs-up"></span></a>
                  </td>
                </tr>
            <?} } else{?>
              <tr>
                <td colspan="7">Não foi encontrado nenhum veículo para revisão.</td>
              </tr>
            <?}?>
          </tbody>
        </table>
        <?if(is_object($this->list) && !isset($this->list->name)){ echo $this->paginationControl($this->list,'Sliding','pagination.phtml'); }?>
      </div>
    </div>
  </div>
</div>

<?foreach($this->list as $body){?>
<form method="post" action="/fleet/accept-review-edited">
  <div class="modal fade" id="accept_<?=$body->vehicle_id?>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title" id="myModalLabel">Aceitar Alteração</h4>
        </div>
        <div class="modal-body">
          Tem certeza que deseja aceitar a alteração deste veículo?
        </div>
        <div class="modal-footer">
            <input type="hidden" value="<?=$body->vehicle_id?>" name="id">
            <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
            <button type="submit" class="btn btn-success">Confirmar</button>
        </div>
      </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
  </div><!-- /.modal -->
</form>

<?}?>