<div class="container">
  <div class="row">
    <div class="col-md-3">
      <div class="list-group">
        <a href="/finance/group-fare" class="list-group-item">
          <h4 class="list-group-item-heading">Grupos Tarifários</h4>
          <p class="list-group-item-text">Gerencie aqui os dados tarifários</p>
        </a>
        <a href="/finance/group-fare-new" class="list-group-item"><i class="fa fa-pencil"></i> Novo</a>
        <a href="/finance/group-fare" class="list-group-item active"><i class="fa fa-search"></i> Pesquisar</a>
      </div>
    </div>
    <div class="col-md-9">
      <ol class="breadcrumb">
        <li><a href="/dashboard">Página inicial</a></li>
        <li><a href="/finance">Financeiro</a></li>
        <li class="active">Grupos Tarifários</li>
      </ol> 
      <hr>
      <div class="page-header">
        <h1>Pesquisa <small>Gerencie os grupos tarifários</small></h1>
        <hr>
          <form class="form-inline" action="/finance/group-fare" method="get" role="form">
            <div class="form-group col-md-5">
              <input type="text" class="form-control" placeholder="nome do grupo tarifário" name="field" value="<?=$this->field?>">
            </div>
            <button type="submit" class="btn btn-primary">Pesquisar</button>
          </form>
          <hr>
        <table class="table table-hover table-bordered">
          <thead>
            <th>Nome do grupo</th>
            <th>Tarifa</th>
          </thead>
          <tbody>
            <?if(count($this->list) && is_object($this->list) && !isset($this->list->name)){
              foreach($this->list as $body){?>
                <tr>
                  <td><a href="/finance/group-fare-edit/id/<?=$body->id?>"><?=$body->name?></a></td>
                  <td>R$ <?=number_format($body->value,2,',','')?></td>
                </tr>
            <?} } else{?>
              <tr>
                <td colspan="7">Não foi encontrada nenhum grupo tarifário na pesquisa.</td>
              </tr>
            <?}?>
          </tbody>
        </table>
        <?if(is_object($this->list) && !isset($this->list->name)){ echo $this->paginationControl($this->list,'Sliding','pagination.phtml'); }?>
      </div>
     </div>
    </div>
  </div>
