<div class="container">
  <div class="row">
    <div class="col-md-3">
      <div class="list-group">
        <a href="/finance" class="list-group-item">
          <h4 class="list-group-item-heading">Financeiro</h4>
            <p class="list-group-item-text">Gerencie aqui os dados financeiros</p>
        </a>
        <a href="/finance/group-fare" class="list-group-item"><i class="fa fa-money"></i> Grupos Tarifários</a>
        <a href="/gsection" class="list-group-item"><i class="fa fa-crop"></i> Grupos de Seções</a>
        <a href="/rate-calculation" class="list-group-item"><i class="fa fa-calculator"></i> Cálculo de Tarifa</a>
      </div>
    </div>
    <div class="col-md-9">
      <ol class="breadcrumb">
        <li><a href="/dashboard">Página inicial</a></li>
        <li class="active">Financeiro</li>
      </ol> 
      <div class="jumbotron">
        <h1>Financeiro</h1>
        <p class="lead">O módulo <b>Financeiro</b> dá suporte à gerência dos grupos tarifários, seções e outras definições financeiras.</p>
      </div>
      <div class="text-center">
        <img class="img-responsive img-thumbnail" src="/img/dinheiro.jpg"><br><br>
      </div>
     </div>
    </div>
  </div>
