<div class="container">
  <div class="row">
    <div class="col-md-3">
      <div class="list-group">
        <a href="/account" class="list-group-item">
          <h4 class="list-group-item-heading">Minha conta</h4>
            <p class="list-group-item-text">Gerencie aqui os dados da sua conta</p>
        </a>
        <a href="/account/personal" class="list-group-item"><i class="fa fa-home"></i> Dados pessoais</a>
        <a href="/account/password" class="list-group-item"><i class="fa fa-key"></i> Redefinição de senha</a>
      </div>
    </div><!--/col-md-->
    <div class="col-md-9">
      <ol class="breadcrumb">
        <li><a href="/dashboard">Página inicial</a></li>
        <li class="active">Minha conta</li>
      </ol>  
      <div class="jumbotron">
        <h1>Configurações <small>deixe seu perfil atualizado</small></h1>
        <p class="lead">Aqui é possível alterar seus dados pessoais, contatos e sua senha.</p>
      </div>
    </div>
  </div>
</div>