<div class="container">
  <div class="row">
    <div class="col-md-3">
      <div class="list-group">
        <a href="/account" class="list-group-item">
          <h4 class="list-group-item-heading">Minha conta</h4>
            <p class="list-group-item-text">Gerencie aqui os dados da sua conta</p>
        </a>
        <a href="/account/personal" class="list-group-item"><i class="fa fa-home"></i> Dados pessoais</a>
        <a href="/account/password" class="list-group-item active"><i class="fa fa-key"></i> Redefinição de senha</a>
      </div>
    </div><!--/col-md-->
    <div class="col-md-9">
    	<ol class="breadcrumb">
        <li><a href="/dashboard">Página inicial</a></li>
        <li><a href="/account">Minha conta</a></li>
        <li class="active">Redefinição de senha</li>
      </ol> 
      <div class="page-header">
      	<h1>Senha <small>defina aqui sua senha</small></h1>
				<hr>
				<form class="form-horizontal" action="/account/password" method="post">
					<div class="form-group">
					    <label class="col-lg-2 control-label" for="old_password">Senha atual</label>
					    <div class="col-lg-5">
					        <input type="password" name="old_password" value="" class="form-control" id="old_password" placeholder="senha atual">
					    </div><!--/.col-lg-5 -->
					</div><!--/.form-group -->
					<div class="form-group">
					    <label class="col-lg-2 control-label" for="password">Nova senha</label>
					    <div class="col-lg-5">
					        <input type="password" name="password" value="" class="form-control" id="password" placeholder="nova senha">
					    </div><!--/.col-lg-5 -->
					</div><!--/.form-group -->
					<div class="form-group">
					    <label class="col-lg-2 control-label" for="confirm_password">Confirme sua nova senha</label>
					    <div class="col-lg-5">
					        <input type="password" name="confirm_password" value="" class="form-control" id="confirm_password" placeholder="confirme sua nova senha">
					    </div><!--/.col-lg-5 -->
					</div><!--/.form-group -->
					<div class="form-group">
						<div class="col-lg-offset-2 col-lg-10">
					    <button type="submit" class="btn btn-primary">Salvar</button>
					  </div>
					</div>
				</form>
      </div>
    </div>
  </div>
</div>