<!-- Wrap all page content here -->
<div id="wrap">
  <!-- Begin page content -->
  <div class="container">
  <?if ($this->save == 'failed') {?>
    <div class="page-header">
      <div class="row">
        <div class="col-md-12 text-center alert alert-danger fade in">
          <button type="button" class="close" data-dismiss="alert">×</button>
          <strong>Ops!</strong> Preencha corretamente o tipo do dia.
        </div>
      </div>
    </div>
    <?}?>
    <div class="row">
    <div class="col-md-3">
      <div class="list-group">
        <a href="/qco" class="list-group-item">
          <h4 class="list-group-item-heading">QCO</h4>
            <p class="list-group-item-text">Gerencie aqui os dados das QCOs</p>
        </a>
        <a href="/qco/calendar" class="list-group-item"><span class="fa fa-calendar"></span> Calendário anual</a>
        <a href="/qco/line-calendar" class="list-group-item"><span class="fa fa-car"></span> Calendário por atendimento</a>
        <a href="/qco/consortium-calendar" class="list-group-item active"><span class="fa fa-building-o"></span> Calendário por delegatária</a>
        <a href="/qco/cell-calendar" class="list-group-item"><span class="fa fa-calendar-o"></span> Calendário por célula operacional</a>
      </div>
    </div>
    	<div class="col-md-9">
      <ol class="breadcrumb">
        <li><a href="/dashboard">Página inicial</a></li>
        <li><a href="/qco">QCO</a></li>
        <li class="active">Pesquisa</li>
      </ol>
      <div class="page-header">
        <h1>Calendário por delegatária <small> cadastre aqui os tipos de dia para o calendário por delegatária</small></h1>
        <hr>
    		<form class="form-horizontal" role="form" id="formCalendar" method="post">
    			<div class="form-group"> 
            <label class="col-sm-3 control-label">Data de início</label>
            <div class="col-sm-9">
            <input class="form-control dateMask" placeholder="Data de início" type="text" name="start_date" id="start_date" value="">
            </div>
            <br><br>
            <label class="col-sm-3 control-label">Data de fim</label>
            <div class="col-sm-9">
            <input class="form-control dateMask" placeholder="Data de fim" type="text" name="end_date" id="end_date" value="">
            </div>
            <br><br>
            <label class="col-sm-3 control-label">Tipo de dia</label>
            <div class="col-sm-9">
              <select class="form-control text-center" name="type_day" id="type_day">
                <option value="0">-- Escolha o tipo de dia --</option>
                <?$calendar = new Application_Model_DbTable_Consortium();
                  $select = $calendar->select()->setIntegrityCheck(false);
                  $select ->from(array('q' => 'qco_type_day'));
                  $row = $calendar->fetchAll($select);?>
                <?foreach($row as $types){?>
                <option value="<?=$types->id?>"><?=$types->name?></option>
                <?}?>
              </select>
            </div>
            <br><br>
            <label class="col-sm-3 control-label">Delegatária</label>
            <div class="col-sm-9">
              <select class="form-control text-center" name="consortium_0" id="consortium_0">
                <option value="0">-- Escolha a delegatária --</option>
                <?$select = $calendar->select()->setIntegrityCheck(false);
                  $select ->from(array('c' => 'consortium'));
                  $row = $calendar->fetchAll($select);?>
                <?foreach($row as $types){?>
                <option value="<?=$types->id?>"><?=$types->name?></option>
                <?}?>
              </select>
            </div>
            <?if($this->number_field != ''){
                for($i=0;$this->number_field > $i;$i++){ ?>
                  <div id="company">
                    <br><br>
                    <label class="col-sm-3 control-label">Delegatária</label>
                    <div class="col-sm-9">
                      <select class="form-control text-center" name="consortium_<?=$i+1?>" id="consortium_<?=$i+1?>">
                        <option value="0">-- Escolha a delegatária --</option>
                        <?$select = $calendar->select()->setIntegrityCheck(false);
                          $select ->from(array('c' => 'consortium'));
                          $row = $calendar->fetchAll($select);?>
                        <?foreach($row as $types){?>
                        <option value="<?=$types->id?>"><?=$types->name?></option>
                        <?}?>
                      </select>
                  </div>
                  </div>
            <?  }
              }?>
    			</div>
				 	<div class="form-group">
				    <div class="col-sm-offset-3 col-sm-9">
              <table border="0">
              <tr>
  				      <td><button type="submit" id='btnCompanyCalendar' class="btn btn-default btn-primary">Gravar</button></td>
                </form>
                <td width="250px"></td>
                <form class="form-horizontal" role="form" id="formFeild" method="post">
                <td><label >Adicione</label></td>
                <td><input class="form-control" size="1" type="text" name="number_field" id="number_field" value=""></td>
                <td><label >delegatárias</label></td>
                <td><button type="submit" id='btnAddCompany' class="btn btn-default btn-primary">Adicionar</button></td>
                </form>
				      </tr>
              </table>
            </div>
				  </div>
        <div class="col-sm-13">
        <br><br>
        <table class="table table-hover table-bordered">
          <thead>
            <th>Data início</th>
            <th>Data fim</th>
            <th>Tipo de dia</th>
            <th>Consórcio</th>
            <th>Excluir</th>
          </thead>
          <tbody>
            <?if(is_object($this->list) && !isset($this->list->consortium)){
              foreach($this->list as $body){?>
                <tr>
                  <td><?=$body->start_date?></td>
                  <td><?=$body->end_date?></td>
                  <?$select = $calendar->select()->setIntegrityCheck(false);
                    $select ->from(array('q' => 'qco_type_day'),array('name'))
                            ->where('q.id = ?',$body->type_day);
                    $row = $calendar->fetchRow($select);?>
                  <td><?=$row->name?></td>
                  <?$select = $calendar->select()->setIntegrityCheck(false);
                    $select ->from(array('c' => 'consortium'),array('name'))
                            ->where('c.id = ?',$body->consortium);
                    $row = $calendar->fetchRow($select);?>
                  <td><?=$row->name?></td>
                  <td><a href="#delete_<?=$body->id?>" class="btn btn-default btn-sm help" data-toggle="modal" title="Excluir o dia"><span class="glyphicon glyphicon-trash"></span></a></td>
                </tr>
            <?} } else{?>
              <tr>
                <td colspan="7">Não foi encontrada nenhuma data pré-cadastrada.</td>
              </tr>
            <?}?>
          </tbody>
        </table>
        <?if(is_object($this->list) && !isset($this->list->name)){ echo $this->paginationControl($this->list,'Sliding','pagination.phtml'); }?>
        </div>
    	</div>
    </div>
  </div> 
</div>

<?foreach($this->list as $body){?>
<form method="post" action="/qco/delete-consortium-calendar/id/<?=$body->id?>">
  <div class="modal fade" id="delete_<?=$body->id?>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title" id="myModalLabel">Excluir</h4>
        </div>
        <div class="modal-body">
          Tem certeza que deseja excluir esta data?
        </div>
        <div class="modal-footer" id="deleteCalendar">
          <input type="hidden" value="<?=$body->id?>" name="id">
          <input type="hidden" value="0" name="action">
          <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
          <input type="submit" id='delete_calendar' class="btn btn-success" value="Excluir">
        </div>
        <div class="modal-footer" id="statusDelete" style="display:none;">
          <div style="margin-right:200px;">
            <img src='/img/loading.gif' id='loading' style="margin-right:40px;">
            <p>Excluindo dados... </p>
          </div>
        </div>
      </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
  </div><!-- /.modal -->
</form>
<?}?>