<div class="container">
  <div class="row">
    <div class="col-md-3">
      <div class="list-group">
        <a href="/qco" class="list-group-item">
          <h4 class="list-group-item-heading">QCO</h4>
            <p class="list-group-item-text">Gerencie aqui os dados das QCOs</p>
        </a>
        <a href="/qco/new" class="list-group-item"><i class="fa fa-pencil"></i> Novo</a>
        <a href="/qco/view" class="list-group-item"><i class="fa fa-search"></i> Pesquisar</a>
        <a href="/qco/export" class="list-group-item active"><i class="fa fa-share"></i> Exportar</a>
        <a href="/qco/report" class="list-group-item"><span class="fa fa-list-alt"></span> Relatórios</a>
      </div>
    </div>
    <div class="col-md-9">
      <ol class="breadcrumb">
        <li><a href="/dashboard">Página inicial</a></li>
        <li><a href="/qco">QCO</a></li>
        <li class="active">Exportar</li>
      </ol> 
      <div class="page-header">
        <h1>Exportar <small>exporte aqui os dados dos QCOs</small></h1>
        <hr>
        <form class="form-inline" action="/qco/export" method="post" role="form">
            <button type="submit" class="btn btn-primary btn-lg">Exportar QCOs</button>
          </form>
        </div>
      </div>
    </div>
  </div>
