<div class="container">
  <div class="row">
    <div class="col-md-12">
      <ol class="breadcrumb">
        <li><a href="/dashboard">Página inicial</a></li>
        <li><a href="/qco/">QCO</a></li>
        <li class="active">Novo</li>
      </ol> 
      <div class="page-header">
        <h1>Novo QCO <small>defina aqui os dados do QCO</small></h1>
        <hr>
        <ul class="nav nav-tabs" id="myTab">
          <li class="active"><a href="#data">Principal</a></li>
        </ul>
        <div class="tab-content">
          <div class="tab-pane active" id="data">
            <hr>
            <?=$this->mainForm?>
          </div>
      </div>
    </div>
  </div>
</div>