<div class="container-fluid">
  <div class="row-fluid">
    <div class="span3">
      <div class="list-group">
        <a href="/qco" class="list-group-item">
          <h4 class="list-group-item-heading">QCO</h4>
            <p class="list-group-item-text">Gerencie aqui os dados das QCOs</p>
        </a>
        <a href="/qco/new" class="list-group-item"><span class="glyphicon glyphicon-pencil"></span> Novo</a>
        <a href="/qco/view" class="list-group-item"><span class="glyphicon glyphicon-search"></span> Pesquisar</a>
        <a href="/qco/export" class="list-group-item"><i class="fa fa-share"></i> Exportar</a>
        <a href="/qco/report" class="list-group-item active"><span class="glyphicon glyphicon-list-alt"></span> Relatórios</a>

      </div>
    </div>
    <div class="span9">
      <ol class="breadcrumb">
        <li><a href="/dashboard">Página inicial</a></li>
        <li><a href="/qco">QCO</a></li>
        <li class="active">Relatórios</li>
      </ol>
      <div class="row-fluid">
        <div class="span6 well">
          <h2>Relação de linhas</h2>
          <p>Lista completa das linhas do sistema.</p>
          <p><a href="#" class="btn btn-default">emitir relatório</a></p>
        </div>
        <div class="span6 well">
          <h2>Movimentação das linhas</h2>
          <p>Lista completa de toda movimentação das linhas ativas no sistema.</p>
          <p><a href="#" class="btn btn-default">emitir relatório</a></p>
        </div>
      </div>
      <div class="row-fluid">
        <div class="span6 well">
          <h2>Composição do Sistema</h2>
          <p>Lista de todas linhas vinculadas e da composição do sistema. </p>
          <p><a href="#" class="btn btn-default">emitir relatório</a></p>
        </div>
      </div>
    </div>
  </div>
</div>