<div class="container">
  <div class="row">
    <div class="col-md-3">
      <div class="list-group">
        <a href="/qco" class="list-group-item">
          <h4 class="list-group-item-heading">QCO</h4>
            <p class="list-group-item-text">Gerencie aqui os dados das QCOs</p>
        </a>
        <a href="/qco/new" class="list-group-item"><i class="fa fa-pencil"></i> Novo</a>
        <a href="/qco/view" class="list-group-item active"><i class="fa fa-search"></i> Pesquisar</a>
        <a href="/qco/export" class="list-group-item"><i class="fa fa-share"></i> Exportar</a>
        <a href="/qco/report" class="list-group-item"><span class="fa fa-list-alt"></span> Relatórios</a>
      </div>
    </div>
    <div class="col-md-9"> 
      <ol class="breadcrumb">
        <li><a href="/dashboard">Página inicial</a></li>
        <li><a href="/qco">QCO</a></li>
        <li class="active">Pesquisa</li>
      </ol>
      <div class="page-header">
        <h1>Pesquisa <small>gerencie aqui os dados dos QCOs</small></h1>
        <hr>
          <form class="form-inline" action="/qco/view" method="get" role="form">
            <div class="form-group col-md-5">
              <input type="text" class="form-control" placeholder="número da linha" name="field" value="<?=$this->field?>">
            </div>
            <button type="submit" class="btn btn-primary">Pesquisar</button>
          </form>
          <hr>
        <table class="table table-hover table-bordered">
          <thead>
            <th>Número da linha</th>
            <th>Nome</th>
            <th>Ações</th>
          </thead>
          <tbody>
            <?if(is_object($this->list) && !isset($this->list->name)){
              foreach($this->list as $body){?>
                <tr>
                  <td><?=$body->number_communication?></a></td>
                  <td><?=$body->name?></td>
                  <td>
                    <a href="/qco/edit/id/<?=$body->id?>" class="btn btn-default btn-sm help" title="Editar QCO"><i class="fa fa-pencil"></i></a>
                    <a href="/qco/vis/id/<?=$body->id?>" class="btn btn-default btn-sm help" title="Visualizar QCO"><i class="fa fa-eye"></i></a>
                  </td>
                </tr>
            <?} } else{?>
              <tr>
                <td colspan="7">Não foi encontrada nenhuma linha na pesquisa.</td>
              </tr>
            <?}?>
          </tbody>
        </table>
        <?if(is_object($this->list) && !isset($this->list->name)){ echo $this->paginationControl($this->list,'Sliding','pagination.phtml'); }?>
      </div>
    </div><!--/span-->
  </div>
</div>