<div class="container">
  <div class="row">
    <div class="col-md-3">
      <div class="list-group">
        <a href="/indicators" class="list-group-item">
          <h4 class="list-group-item-heading">Indicadores</h4>
            <p class="list-group-item-text">Gerencie aqui a Apuração de Indicadores</p>
        </a>
        <a href="/accident" class="list-group-item"><i class="fa fa-ambulance"></i> Acidentes</a>
      </div>
    </div>
    <div class="col-md-9">
      <ol class="breadcrumb">
        <li><a href="/dashboard">Página inicial</a></li>
        <li class="active">Indicadores</li>
      </ol> 
      <div class="jumbotron">
        <h1>Indicadores</h1>
        <p class="lead">O módulo <b>Indicadores</b> dá suporte à apuração de dados e síntese de informações.</p>
      </div>
      <div class="text-center">
        <img class="img-responsive img-thumbnail" src="/img/grafico.jpg"><br><br>
      </div>
     </div>
    </div>
  </div>