<div class="container">
  <div class="row">
    <div class="col-md-3">
      <div class="list-group">
        <a href="/gsection" class="list-group-item">
          <h4 class="list-group-item-heading">Grupo de Seção</h4>
            <p class="list-group-item-text">Gerencie aqui os dados sobre os Grupos de Seção</p>
        </a>
        <a href="/gsection/new" class="list-group-item"><i class="glyphicon glyphicon-arrow-up"></i> Upload da Tabela Tarifária</a>
        <a href="/gsection/view" class="list-group-item"><span class="fa fa-bar-chart-o"></span> Visualização</a>
      </div>
    </div>
    <div class="col-md-9">
      <ol class="breadcrumb">
        <li><a href="/dashboard">Página inicial</a></li>
        <li class="active">Grupo de Seção</li>
      </ol> 
      <div class="jumbotron">
        <h1>Grupo de Seção</h1>
        <p class="lead">O módulo <b>Grupo de Seções</b> dá suporte à gerência dos grupos tarifários de linhas seccionadas.</p>
      </div>
      <div class="text-center">
        <img class="img-responsive img-thumbnail" src="/img/rouxinol.jpg"><br><br>
      </div>
     </div>
    </div>
  </div>
