<div class="container">
  <div class="row">
    <div class="col-md-3">
      <div class="list-group">
        <a href="/gsection" class="list-group-item">
          <h4 class="list-group-item-heading">Grupo de Seções</h4>
            <p class="list-group-item-text">Gerencie aqui os dados sobre os Grupos de Seções</p>
        </a>
        <a href="/gsection/new" class="list-group-item"><i class="glyphicon glyphicon-arrow-up"></i> Upload da Tabela Tarifária</a>
        <a href="/gsection/view" class="list-group-item active"><span class="fa fa-bar-chart-o"></span> Visualização</a>
      </div>
    </div>
    <div class="col-md-9">
      <ol class="breadcrumb">
        <li><a href="/dashboard">Página inicial</a></li>
        <li class="active"> Tabelas Tarifárias</li>
      </ol> 
      <div class="page-header">
        <h1>Tabelas Tarifárias - Linhas Seccionadas <br>
      </div>
      <form class="form-inline" action="/gsection/view" method="get" role="form">
          <div class="form-group col-md-4">
    		    <input type="text" class="form-control search-query" placeholder="Pesquisa" name="field" value="<?=$this->field?>">
          </div>
          <div class="form-group col-md-3">
            <select name="optionSearch" class="form-control">
              <option value="0" selected="selected">Pesquisar por:</option>
              <option value="1" <?if($this->optionSearch == 1) echo "selected='selected'"; ?>>Número de Comunicação</option>
              <option value="2" <?if($this->optionSearch == 2) echo "selected='selected'"; ?>>Nome da Linha</option>
              <option value="3" <?if($this->optionSearch == 3) echo "selected='selected'"; ?>>Tarifa Antiga</option>
              <option value="4" <?if($this->optionSearch == 4) echo "selected='selected'"; ?>>Tarifa Vigente</option>
            </select>
          </div>
          <button type="submit" class="btn btn-primary">Pesquisar</button>
      	 </form>
      	 <hr>
      <div class="col-xs-12 col-sm-12">
      <table class="table table-bordered table-hover" align="center">
      	<thead>
      		<tr>
      			<th>Número Comunicação</th>
      			<th>Nome da Linha</th>
      			<th>Tarifa Antiga</th>
      			<th>Tarifa Atual</th>
      		</tr>
      	</thead>
      	<tbody>
      	<?if(count($this->list))
      		{
    				foreach ($this->list as $data){?>
		      		<tr>
		      				<tr>
		      					<td><?=$data->num_comunication?></td>
		      					<td><?=$data->line_name?></td>
		      					<td><?=str_replace(".", ",", $data->old_fare)?></td>
		      					<td><?=str_replace(".", ",", $data->new_fare)?></td>
		      				</tr>
		      		</tr>
      			<?}
      		}?>
      	</tbody>
      </table>
      <?if(is_object($this->list) && !isset($this->list->name)){ echo $this->paginationControl($this->list,'Sliding','pagination.phtml'); }?>
      </div>
    </div>
  </div>
</div>