
    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span3">
          <div class="list-group">
            <a href="#" class="list-group-item">
              <h4 class="list-group-item-heading">Usuários</h4>
            </a>
            <a href="/administration/user-new" class="list-group-item">Novo</a>
            <a href="/administration/user" class="list-group-item">Pesquisar</a>
          </div>

          <div class="list-group">
            <a href="#" class="list-group-item">
              <h4 class="list-group-item-heading">Cidades</h4>
            </a>
            <a href="/administration/city-new" class="list-group-item">Novo</a>
            <a href="/administration/city" class="list-group-item active">Pesquisar</a>
          </div>

          <div class="list-group">
            <a href="#" class="list-group-item">
              <h4 class="list-group-item-heading">Padrão de Veículo</h4>
            </a>
            <a href="/administration/pattern-new" class="list-group-item">Novo</a>
            <a href="/administration/pattern" class="list-group-item">Pesquisar</a>
          </div>

          <div class="list-group">
            <a href="#" class="list-group-item">
              <h4 class="list-group-item-heading">Modelos de Chassi</h4>
            </a>
            <a href="/administration/chassi-new" class="list-group-item">Novo</a>
            <a href="/administration/chassi" class="list-group-item">Pesquisar</a>
          </div>

          <div class="list-group">
            <a href="#" class="list-group-item">
              <h4 class="list-group-item-heading">Tipos de Veículo</h4>
            </a>
            <a href="/administration/type-new" class="list-group-item">Novo</a>
            <a href="/administration/type" class="list-group-item">Pesquisar</a>
          </div>

          <div class="list-group">
            <a href="#" class="list-group-item">
              <h4 class="list-group-item-heading">Cores</h4>
            </a>
            <a href="/administration/color-new" class="list-group-item">Novo</a>
            <a href="/administration/color" class="list-group-item">Pesquisar</a>
          </div>

          <div class="list-group">
            <a href="#" class="list-group-item">
              <h4 class="list-group-item-heading">Carroceria</h4>
            </a>
            <a href="/administration/body-new" class="list-group-item">Novo</a>
            <a href="/administration/body" class="list-group-item">Pesquisar</a>
          </div>
        </div><!--/span-->
        <div class="span9">
          <div class="page-header">
            <h1>Pesquisa <small>gerencie aqui os dados das cidades</small></h1>
            <hr>
            <form class="form-inline" action="/administration/city" method="get" role="form">
              <div class="form-group col-md-5">
                <input type="text" class="form-control" placeholder="nome da carroceria" name="field" value="<?=$this->field?>">
              </div>
              <button type="submit" class="btn btn-primary">Pesquisar</button>
            </form>
            <hr>
            <table class="table table-hover table-bordered">
              <thead>
                <th>Nome</th>
              </thead>
              <tbody>
                <?if(is_object($this->list) && !isset($this->list->name)){
                  foreach($this->list as $city){?>
                    <tr>
                      <td><a href="/administration/city-edit/id/<?=$city->id?>"><?=$city->name?></a></td>
                    </tr>
                <?} } else{?>
                  <tr>
                    <td colspan="7">Não encontrado nenhum fiscal na pesquisa.</td>
                  </tr>
                <?}?>
              </tbody>
            </table>
            <?if(is_object($this->list) && !isset($this->list->name)){ echo $this->paginationControl($this->list,'Sliding','pagination.phtml'); }?>
          </div>
        </div><!--/span-->
      </div><!--/row-->