
    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span3">
          <div class="list-group">
            <a href="#" class="list-group-item">
              <h4 class="list-group-item-heading">Usuários</h4>
            </a>
            <a href="/administration/user-new" class="list-group-item">Novo</a>
            <a href="/administration/user" class="list-group-item">Pesquisar</a>
          </div>

          <div class="list-group">
            <a href="#" class="list-group-item">
              <h4 class="list-group-item-heading">Cidades</h4>
            </a>
            <a href="/administration/city-new" class="list-group-item">Novo</a>
            <a href="/administration/city" class="list-group-item">Pesquisar</a>
          </div>

          <div class="list-group">
            <a href="#" class="list-group-item">
              <h4 class="list-group-item-heading">Padrão de Veículo</h4>
            </a>
            <a href="/administration/pattern-new" class="list-group-item">Novo</a>
            <a href="/administration/pattern" class="list-group-item">Pesquisar</a>
          </div>

          <div class="list-group">
            <a href="#" class="list-group-item">
              <h4 class="list-group-item-heading">Modelos de Chassi</h4>
            </a>
            <a href="/administration/chassi-new" class="list-group-item">Novo</a>
            <a href="/administration/chassi" class="list-group-item">Pesquisar</a>
          </div>

          <div class="list-group">
            <a href="#" class="list-group-item">
              <h4 class="list-group-item-heading">Tipos de Veículo</h4>
            </a>
            <a href="/administration/type-new" class="list-group-item">Novo</a>
            <a href="/administration/type" class="list-group-item">Pesquisar</a>
          </div>

          <div class="list-group">
            <a href="#" class="list-group-item">
              <h4 class="list-group-item-heading">Cores</h4>
            </a>
            <a href="/administration/color-new" class="list-group-item active">Novo</a>
            <a href="/administration/color" class="list-group-item">Pesquisar</a>
          </div>

          <div class="list-group">
            <a href="#" class="list-group-item">
              <h4 class="list-group-item-heading">Carroceria</h4>
            </a>
            <a href="/administration/body-new" class="list-group-item">Novo</a>
            <a href="/administration/body" class="list-group-item">Pesquisar</a>
          </div>
        </div><!--/span-->
        <div class="span9">   
          <div class="page-header">
            <h1>Cores <small>defina aqui os dados da cor</small></h1>
            <hr>
            <?=$this->form?>
          </div>
        </div><!--/span-->
      </div><!--/row-->