<!DOCTYPE html>
<html lang="pt_BR">
  <head>
    <meta charset="utf-8">
    <title>SIMETRO</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    <link href="/css/bootstrap.min.css" rel="stylesheet">
    <style type="text/css">
      body {
        padding-top: 80px;
      }

    </style>
    <link href="/css/bootstrap-responsive.min.css" rel="stylesheet">
    <link href="/css/font-awesome.min.css" rel="stylesheet">
    <link href="/css/datepicker.css" rel="stylesheet">
    <link href="/css/general.css" rel="stylesheet">
    <?if($this->treatment){?>
    <link href="/css/fullcalendar.css" rel="stylesheet">
    <link href="/css/fullcalendar.print.css" rel="stylesheet">
    <?}?>

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="/js/html5shiv.js"></script>
      <script src="/js/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>

    <? 
      $authNamespace = new Zend_Session_Namespace('userInformation');
      $institution = $authNamespace->institution;
      $userId = $authNamespace->user_id; 
    ?>

    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/dashboard">SIMETRO</a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <?if($institution == 1){?>
            <li><a href="/fleet/view">Frota</a></li>
            <li class="dropdown">
              <a href="#qco" class="dropdown-toggle" data-toggle="dropdown">QCO <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="/qco"><i class="fa fa-road"></i> Gestão de QCO</a></li>
                <li><a href="/qco/calendar"><i class="fa fa-calendar"></i> Calendário</a></li>
              </ul>
            </li>
            <li><a href="/mco/view">MCO</a></li>



            <li class="dropdown">
              <a href="#finance" class="dropdown-toggle" data-toggle="dropdown">Financeiro <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="/finance/group-fare"><i class="fa fa-money"></i> Grupos Tarifários</a></li>
                <li> <a href="/gsection"><i class="fa fa-crop"></i> Grupos de Seções</a></li>
                <li> <a href="/rate-calculation"><i class="fa fa-calculator"></i> Cálculo de Tarifa</a></li>
              </ul>
            </li>

            <li class="dropdown">
              <a href="#indicators" class="dropdown-toggle" data-toggle="dropdown">Indicadores <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="/accident"><i class="fa fa-ambulance"> </i> Acidentes </a></li>
                 <!--<li> <a href="/gsection"><i class="fa fa-crop"></i> Grupos de Seções</a></li>
                <li> <a href="/rate-calculation"><i class="fa fa-calculator"></i> Cálculo de Tarifa</a></li> -->
              </ul>
            </li>


            <?}?>
            <?if($institution == 2){?>
            <li><a href="/inspection">Vistoria</a></li>
            <li><a href="/scheduling">Agendamento Online</a></li>
            <?}?>
            <?if($institution == 3 || $institution == 4){?>
            <li><a href="/fleet">Frota</a></li>
            <?}?>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li>
              <a href="/mail/inbox">
                Caixa de Mensagens 
              </a>
            </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="glyphicon glyphicon-user"></i><b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="/account"><i class="fa fa-wrench"></i> Minha conta</a></li>
                <?if($institution == 1){?>
                <li> <a href="/administration"><i class="fa fa-eye"></i> Administração</a></li>
                <?}?>
                <li class="divider"></li>
                <li> <a href="/auth/logout"><i class="fa fa-sign-out"></i> Sair</a></li>
              </ul>
            </li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">

      <?
        switch ($this->save) {
          case 'success':
            $title = 'Ok!';
            $message = 'Dados atualizados com sucesso.';
            $class = 'success';
            break;

          case 'registered':
            $title = 'Próximo passo:';
            $message = 'Finalize a inserção das informações e anexe os documentos para o agendamento da vistoria.';
            $class = 'success';
            break;

          case 'waiting':
            $title = 'Ok!';
            $message = 'Continue com a inserção dos dados.';
            $class = 'success';
            break;

          case 'error':
            $title = 'Ops!';
            $message = ' Houve algum erro na inserção dos dados. Tente novamente preenchendo os dados corretamente.';
            $class = 'danger';
            break;
            
          case 'exists':
            $title = 'Ops!';
            $message = ' Houve algum erro na inserção dos dados. Eles já estão inseridos no sistema.';
            $class = 'danger';
            break;

          case 'scheduling_error':
            $title = 'Ops!';
            $message = ' Não é permitido realizar agendamento para o dia corrente. São necessárias pelo menos 24h de antecedência.';
            $class = 'danger';
            break;

          default:
            $title = 'Ops!';
            $message = 'Houve algum erro na inserção dos dados. Tente novamente preenchendo os dados corretamente.';
            $class = 'danger';
            break;
        }
      ?>
      <?if($this->save){?>
      <div class="row">
        <div class="col-md-12 text-center alert alert-<?=$class?> fade in">
          <button type="button" class="close" data-dismiss="alert">×</button>
          <h3><?=$title?></h3> <?=$message?>
        </div>
      </div>
      <?}?>
      <?if($this->password_error){?>
      <div class="row">
        <div class="col-md-12 text-center alert alert-danger fade in">
          <button type="button" class="close" data-dismiss="alert">×</button>
          <strong>Ops!</strong> Senha antiga não confere ou senhas não conferem.
        </div>
      </div>
      <?}?>

      <?php echo $this->layout()->content; ?>

    </div>
    
    <script src="/js/jquery-1.10.1.min.js"></script>
    <script src="/js/jquery.maskedinput.min.js"></script>
    <script src="/js/bootstrap.min.js"></script>
    <script src="/js/bootstrap-datepicker.js"></script>
    <script src="/js/locales/bootstrap-datepicker.pt-BR.js"></script>
    <script src="/js/language/pt-BR.js"></script>
    <script src="/js/d3.v3.min.js"></script>
    <script src="/js/bootstrap3-typeahead.min.js"></script>
    <script src="/js/jquery.typing-0.2.0.min.js"></script>
    <script src="/js/general_2.js"></script>
    <?if($this->accident){?>
    <script src="/js/accident.js"></script>
    <?}?>
    <?if($this->treatment){?>
    <script src="/js/fullcalendar.js"></script>
    <script src="/js/gcal.js"></script>
    <script src="/js/jquery.livequery.js"></script>
    <script src="/js/scheduling_v3.js"></script>
    <?}else{?>
    <script src="/js/schedule.js"></script>
    <?}?>

</html>
