
<!DOCTYPE html>
<html lang="pt_BR">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Um sistema de gestão do transporte municipal">
    <meta name="author" content="SETOP">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>IMTT | Ônibus Municipal</title>

    <!-- Bootstrap core CSS -->
    <link href="/css/bootstrap.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="/css/signin.css" rel="stylesheet">

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="/js/html5shiv.js"></script>
      <script src="/js/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <div class="container">

      <form class="form-signin" method="post" action="/auth/login">
        <? if($this->error){ ?>
          <div class="alert alert-danger fade in" role="alert">
            <button type="button" class="close" data-dismiss="alert">×</button>
            <strong>Ops!</strong> Usuário e/ou senha errados.
          </div>
        <? } ?>
        <h2 class="form-signin-heading">Faça o login</h2>
        <input type="text" name="username" class="form-control" placeholder="login" autofocus>
        <input type="password" name="password" class="form-control" placeholder="senha">
        <button class="btn btn-lg btn-primary btn-block" type="submit">Entrar</button>
      </form>

    </div> <!-- /container -->

  </body>
</html>
