<div class="container">
  <div class="row">
    <div class="col-md-3">
      <div class="list-group">
        <a href="/validator" class="list-group-item">
          <h4 class="list-group-item-heading">Validador</h4>
            <p class="list-group-item-text">Gerencie aqui os dados dos validadores</p>
        </a>
        <?if($this->institution == 3){?>
        <a href="/validator/new" class="list-group-item"><i class="fa fa-pencil"></i> Novo</a>
        <a href="/validator/view" class="list-group-item"><i class="fa fa-search"></i> Pesquisar</a>
        <?}?>
      </div>
    </div>
    <div class="col-md-9">
      <ol class="breadcrumb">
        <li><a href="/dashboard">Página inicial</a></li>
        <li class="active">Validador</li>
      </ol>  
      <div class="page-header">
        <h1>Cadastro de validador <small> cadastre aqui os validadores</small></h1>
        <hr>
        <form class="form-horizontal" role="form" id="formValidator" method="post">
          <div class="form-group"> 
            <label class="col-sm-3 control-label">Número do validor</label>
            <div class="col-sm-9">
            <input class="form-control" placeholder="Número do validador" type="text" name="number" id="number" value="">
            </div>
            <br><br>
            <label class="col-sm-3 control-label">Serial</label>
            <div class="col-sm-9">
            <input class="form-control" placeholder="Número do serial" type="text" name="serial" id="serial" value="">
            </div>
            <br><br>
            <label class="col-sm-3 control-label">Tipo do validor</label>
            <div class="col-sm-9">
              <select class="form-control text-center" name="type" id="type">
                <option value="0">-- Escolha o tipo do validador --</option>
                <option value="1">Principal</option>
                <?if($this->percentage == 0){
                    echo"<option value='2'>Reserva</option>";
                }?>
              </select>
            </div>
          </div>
          <div class="form-group">
            <div class="col-sm-offset-3 col-sm-7">
              <button type="submit" id='btnCalendar' class="btn btn-default btn-primary">Salvar</button>
            </div>
          </div>
        </form>
      </div>
     </div>
    </div>
  </div>