<div class="container">
  <div class="row">
    <div class="col-md-3">
      <div class="list-group">
        <a href="/validator" class="list-group-item">
          <h4 class="list-group-item-heading">Validador</h4>
            <p class="list-group-item-text">Gerencie aqui os dados dos validadores</p>
        </a>
        <?if($this->institution == 3){?>
        <a href="/validator/new" class="list-group-item"><i class="fa fa-pencil"></i> Novo</a>
        <a href="/validator/view" class="list-group-item"><i class="fa fa-search"></i> Pesquisar</a>
        <?}?>
      </div>
    </div>
    <div class="col-md-9">
      <ol class="breadcrumb">
        <li><a href="/dashboard">Página inicial</a></li>
        <li class="active">Validador</li>
      </ol>  
      <div class="page-header">
        <h1>Pesquisa <small> Gerencie aqui os dados dos validadores</small></h1>
        <hr>
        <div class="col-sm-13">
        <br><br>
        <table class="table table-hover table-bordered">
          <thead>
            <th>Número</th>
            <th>Serial</th>
            <th>Tipo de validador</th>
            <th>Excluir</th>
          </thead>
          <tbody>
            <?
            $validator = new Application_Model_DbTable_Validator();
            if(is_object($this->list) && !isset($this->list->number)){
              foreach($this->list as $body){?>
                <tr>
                  <td><?=$body->number?></td>
                  <td><?=$body->serial?></td>
                  <?if($body->type == 1){?>
                    <td>Principal</td>
                  <?}else{?>
                    <td>Reserva</td>
                  <?}?>
                  <td><a href="#delete_<?=$body->id?>" class="btn btn-default btn-sm help" data-toggle="modal" title="Excluir"><span class="glyphicon glyphicon-trash"></span></a></td>
                </tr>
            <?}} else{?>
              <tr>
                <td colspan="7">Não foi encontrada nenhum validador cadastrado.</td>
              </tr>
            <?}?>
          </tbody>
        </table>
        <?if(is_object($this->list) && !isset($this->list->name)){ echo $this->paginationControl($this->list,'Sliding','pagination.phtml'); }?>
        </div>
      </div>
     </div>
    </div>
  </div>

  <?foreach($this->list as $body){?>
<form method="post" action="/validator/delete-validator/id/<?=$body->id?>">
  <div class="modal fade" id="delete_<?=$body->id?>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title" id="myModalLabel">Excluir</h4>
        </div>
        <div class="modal-body">
          Tem certeza que deseja excluir este validador?
        </div>
        <div class="modal-footer" id="deleteValidator">
          <input type="hidden" value="<?=$body->id?>" name="id">
          <input type="hidden" value="0" name="action">
          <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
          <input type="submit" id='delete_validator' class="btn btn-success" value="Excluir">
        </div>
        <div class="modal-footer" id="statusDelete" style="display:none;">
          <div style="margin-right:200px;">
            <img src='/img/loading.gif' id='loading' style="margin-right:40px;">
            <p>Excluindo dados... </p>
          </div>
        </div>
      </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
  </div><!-- /.modal -->
</form>
<?}?>