<div class="container">
  <div class="row">
    <div class="col-md-3">
      <div class="list-group">
        <a href="/accident" class="list-group-item">
          <h4 class="list-group-item-heading">Acidentes</h4>
            <p class="list-group-item-text">Gerencie aqui os dados sobre os acidentes</p>
        </a>
        <a href="/accident/new" class="list-group-item"><i class="glyphicon glyphicon-arrow-up"></i> Upload do Arquivo REDS</a>
        <a href="/accident/view" class="list-group-item"><span class="glyphicon glyphicon-search"></span> Pesquisar</a>
        <a href="/accident/report" class="list-group-item"><i class="fa fa-list-alt"></i> Relatórios</a>
        <a href="/accident/vis" class="list-group-item"><span class="fa fa-bar-chart-o"></span> Visualização</a>
      </div>
    </div>
    <div class="col-md-9">
      <ol class="breadcrumb">
        <li><a href="/dashboard">Página inicial</a></li>
        <li class="active">Acidentes</li>
      </ol> 
      <div class="jumbotron">
        <h1>Acidentes</h1>
        <p class="lead">O módulo <b>Acidentes</b> dá suporte à gerência dos dados de acidentes da frota.</p>
      </div>
      <div class="text-center">
        <img class="img-responsive img-thumbnail" src="/img/SAMU.jpg"><br><br>
      </div>
     </div>
    </div>
  </div>
