<div class="container"><br>
  <table style="text-align: center; height: 60%;width: 80%; margin: 0 auto" class="table table-bordered" border='2'>
      <tr>
        <th style="border: 2px solid white; border-color: #000; height: 185px ;width: 200px"><img alt="" src="/img/brasao2.jpg" height="100%" width="100%" align="center"></th>
        <th style="border: 2px solid white; border-color: #000; text-align: center; line-height: 55px"><font size="3" face="verdana">Superintendência de Transporte Metropolitano</font><br>
        <img width="100%" src="/img/barra.jpg"><br><font face="verdana" size="3">Relatório de Acidentes por Período</font></th>
      </tr><br>
    </table><br>
    <h3 align="center">Perído de Referência: <?=Application_Model_General::dateToBr($this->list2)?> até <?=Application_Model_General::dateToBr($this->list3)?></h3>
	<div class="row">
	</div>
  <div class="row">
    <div class="col-sm-6"><br><br>
      <table class="table table-bordered table-hover" border="1">
        <thead>
          <tr>
            <th>RIT</th>
            <th>Quantidade</th>
          </tr>
        </thead>
        <tbody>
          <?if(count($this->listRit)) 
          { $totalAmount = 0;
            foreach ($this->listRit as $value)
             {?>
              <tr>
                <td><?if($value->rit == '') echo 'Sem RIT'; else echo $value->rit;?></td>
                <td><?=$value->amount?></td>
              </tr>
            <?$totalAmount+=$value->amount;}}?>
            <tr>
              <td><b>Total</b></td>
              <td><b><?=$totalAmount?></b></td>
            </tr>
        </tbody>
      </table>
    </div>
    <div class="col-sm-6"><br><br>
      <table class="table table-bordered table-hover" border="1">
        <thead>
          <tr>
            <th>Cidade</th>
            <th>Quantidade</th>
          </tr>
        </thead>
        <tbody>
          <?if(count($this->listCity)) 
          { $totalAmount = 0;
            foreach ($this->listCity as $value)
             {?>
              <tr>
                <td><?=$value->name?></td>
                <td><?=$value->amount?></td>
              </tr>
            <?$totalAmount+=$value->amount;}}?>
            <tr>
              <td><b>Total</b></td>
              <td><b><?=$totalAmount?></b></td>
            </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>