<div class="container">
  <div class="row">
    <div class="col-md-3">
      <div class="list-group">
        <a href="/accident" class="list-group-item">
          <h4 class="list-group-item-heading">Acidentes</h4>
            <p class="list-group-item-text">Gerencie aqui os dados dos Acidentes</p>
        </a>
        <a href="/accident/new" class="list-group-item"><i class="glyphicon glyphicon-arrow-up"></i> Upload do Arquivo REDS</a>
        <a href="/accident/view" class="list-group-item active"><span class="glyphicon glyphicon-search"></span> Pesquisar</a>
        <a href="/accident/report" class="list-group-item"><span class="fa fa-list-alt"></span> Relatórios</a>
        <a href="/accident/vis" class="list-group-item"><span class="fa fa-bar-chart-o"></span> Visualização</a>
      </div>
    </div>
    <div class="col-md-9">
      <ol class="breadcrumb">
        <li><a href="/dashboard">Página inicial</a></li>
        <li><a href="/accident">Acidentes</a></li>
        <li class="active">Visualização</li>
      </ol>
      <div class="page-header">
        <h1>Visualização <small>gerencie aqui os dados dos Acidentes</small></h1>
        <hr>
          <form class="form-inline" action="/accident/view" method="get" role="form">
            <div class="form-group col-md-5 row">
      				<div class="col-md-6"><input type="text" class="form-control" placeholder="DD/MM/AAAA" name="ini_date" value="<?=$this->ini_date?>"><br /><br></div>
              <div class="col-md-6"><input type="text" class="form-control" placeholder="DD/MM/AAAA" name="end_date" value="<?=$this->ini_date?>"><br /><br></div>
            </div>
            <button type="submit" class="btn btn-primary">Pesquisar</button>
          </form>
          <hr>
        <table class="table table-hover table-bordered">
          <thead>
            <th>Arquivo de referência</th>
            <th>Ações</th>
          </thead>
          <tbody>
            <?if(is_object($this->list) && !isset($this->list->name)){
              foreach($this->list as $body){?>
                <tr>
                  <td><a href="/accident/edit/id/<?=$body->id?>"><?=$body->month_ini."/".$body->year_ini?></a></td>
                  <td><a href="#delete_<?=$body->id?>" class="btn btn-default btn-sm help" data-toggle="modal" title="Excluir o arquivo"><span class="glyphicon glyphicon-trash"></span></a></td>
                </tr>
            <?} } else{?>
              <tr>
                <td colspan="7">Não foi encontrada nenhuma linha na pesquisa.</td>
              </tr>
            <?}?>
          </tbody>
        </table>
        <?if(is_object($this->list) && !isset($this->list->name)){ echo $this->paginationControl($this->list,'Sliding','pagination.phtml'); }?>
      </div>
    </div><!--/span-->
  </div>
  <?foreach($this->list as $body){?>
		<form method="post" action="/accident/delete">
		  <div class="modal fade" id="delete_<?=$body->id?>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		    <div class="modal-dialog">
		      <div class="modal-content">
		        <div class="modal-header">
		          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
		          <h4 class="modal-title" id="myModalLabel">Excluir</h4>
		        </div>
		        <div class="modal-body">
		          Tem certeza que deseja excluir esse arquivo?
		        </div>
		        <div class="modal-footer">
		          <input type="hidden" value="<?=$body->id?>" name="id">
		          <?
		            $ini_date = $body->ini_date;
		            $end_date = $body->end_date;
		          ?>
		          <input type="hidden" value="<?=$ini_date?>" name="ini_date">
		          <input type="hidden" value="<?=$ini_date?>" name="end_date">
		          <input type="hidden" value="0" name="action">
		          <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
		          <input type="submit" class="btn btn-success" value="Excluir">
		        </div>
		      </div><!-- /.modal-content -->
		    </div><!-- /.modal-dialog -->
		  </div><!-- /.modal -->
		</form>
	<?}?>
</div>