<div class="container">
  <div class="row">
    <div class="col-md-12">
      <ol class="breadcrumb">
        <li><a href="/dashboard">Página inicial</a></li>
        <li class="active">Caixa de Mensagens</li>
      </ol>  
      <div class="collumn">
        <div class="span6 well">
          <h2>Caixa de entrada</h2>
          <p>Veja as mensagens recebidas de outros usuário.</p>
          <p><a href="/mail/inbox" class="btn btn-default">Inbox</a></p>
        </div>
        <div class="span6 well">
          <h2>Caixa de saida</h2>
          <p>Acesse mensagens encaminhadas a outros usuários.</p>
          <p><a href="/mail/outbox" class="btn btn-default">Outbox</a></p>
        </div>
      </div>
      <div class="text-center">
		    <img src='/img/mail.jpg' class="img-responsive img-thumbnail" title="mail"><br><br>
		  </div>
    </div>
  </div>
  </div>